### ISSUE TITLE
Flee should be more fair

### ISSUE THREAD

**Issue by cormacmccarthy** [deck-monsters/deck-monsters#76]
If a monster flees:

- [ ] The remaining monster gets 1 more turn
- [ ] The fleeing monster should be counted as a loser (and be awarded 75% of lose xp)
- [ ] The remaining monster should be counted as a winner (and get 75% win xp)
- [x] Bosses can not flee

**Comment by tweettypography** [comment]
Not sure that I agree with the fleeing monster being a loser but I do think this will all change if we switch to a system where you get xp for the monsters you are responsible for killing. In that system you wouldn't get the "win" xp bonus but you would get any xp for monsters you were responsible for.

**Comment by RodEsp** [comment]
#101 addresses this to a degree.
It makes it so that if a monster flees in a 1 v 1 battle it will be counted as a draw and nobody will gain any XP.
In a multiplayer battle it depends. If a monster kills any other monster it will get XP based on the level difference between itself and the monster it killed, regardless of whether it fled or not. But a monster that flees will only cause its owner to gain the `XP_PER_DEFEAT` which is `1` right now.
If all but 1 monster flee then nobody will gain any XP, like in the 1v1 scenario.

**Comment by cormacmccarthy** [comment]
I think the way it is now will actually be ok, especially once we get some non-ring battle options.
